#on:
#  push:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master
#name: ğŸš€ Deploy website on push
#jobs:
#  web-deploy:
#    name: ğŸ‰ Deploy
#    runs-on: ubuntu-latest
#    steps:
#      - name: ğŸšš Get latest code
#        uses: actions/checkout@v2.3.2
#
#      - name: ğŸ”— Install dependencies
#        run: npm install
#
#      - name: ğŸ”¨ Build Project
#        run: npm run build
#
#      - name: ğŸ“‚ Sync files
#        uses: SamKirkland/FTP-Deploy-Action@4.0.0
#        with:
#          server: fifaurban.savana-hosting.cz
#          username: fifaurban
#          password: ${{ secrets.ftp_password }}
#          server-dir: /lukrastav.cz/
#
#      - name: ğŸ—‘ï¸ Remove Cache
#        uses: JesseTG/rm@v1.0.2
#        with:
#          path: /lukrastav.cz/temp/cache
